'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/NewConnect", ReplyAction:="http://tempuri.org/IService1/NewConnectResponse")>  _
        Function NewConnect(ByVal name As String) As myLib.Player
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/NewConnect", ReplyAction:="http://tempuri.org/IService1/NewConnectResponse")>  _
        Function NewConnectAsync(ByVal name As String) As System.Threading.Tasks.Task(Of myLib.Player)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SendMessage", ReplyAction:="http://tempuri.org/IService1/SendMessageResponse")>  _
        Sub SendMessage(ByVal text As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SendMessage", ReplyAction:="http://tempuri.org/IService1/SendMessageResponse")>  _
        Function SendMessageAsync(ByVal text As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetChatText", ReplyAction:="http://tempuri.org/IService1/GetChatTextResponse")>  _
        Function GetChatText() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetChatText", ReplyAction:="http://tempuri.org/IService1/GetChatTextResponse")>  _
        Function GetChatTextAsync() As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetGame", ReplyAction:="http://tempuri.org/IService1/GetGameResponse")>  _
        Function GetGame() As myLib.Game
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetGame", ReplyAction:="http://tempuri.org/IService1/GetGameResponse")>  _
        Function GetGameAsync() As System.Threading.Tasks.Task(Of myLib.Game)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function NewConnect(ByVal name As String) As myLib.Player Implements ServiceReference1.IService1.NewConnect
            Return MyBase.Channel.NewConnect(name)
        End Function
        
        Public Function NewConnectAsync(ByVal name As String) As System.Threading.Tasks.Task(Of myLib.Player) Implements ServiceReference1.IService1.NewConnectAsync
            Return MyBase.Channel.NewConnectAsync(name)
        End Function
        
        Public Sub SendMessage(ByVal text As String) Implements ServiceReference1.IService1.SendMessage
            MyBase.Channel.SendMessage(text)
        End Sub
        
        Public Function SendMessageAsync(ByVal text As String) As System.Threading.Tasks.Task Implements ServiceReference1.IService1.SendMessageAsync
            Return MyBase.Channel.SendMessageAsync(text)
        End Function
        
        Public Function GetChatText() As String Implements ServiceReference1.IService1.GetChatText
            Return MyBase.Channel.GetChatText
        End Function
        
        Public Function GetChatTextAsync() As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.GetChatTextAsync
            Return MyBase.Channel.GetChatTextAsync
        End Function
        
        Public Function GetGame() As myLib.Game Implements ServiceReference1.IService1.GetGame
            Return MyBase.Channel.GetGame
        End Function
        
        Public Function GetGameAsync() As System.Threading.Tasks.Task(Of myLib.Game) Implements ServiceReference1.IService1.GetGameAsync
            Return MyBase.Channel.GetGameAsync
        End Function
    End Class
End Namespace
