'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServiceReference1
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Player", [Namespace]:="http://schemas.datacontract.org/2004/07/myLib"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Player
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private IDField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NameField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ID() As Integer
            Get
                Return Me.IDField
            End Get
            Set
                If (Me.IDField.Equals(value) <> true) Then
                    Me.IDField = value
                    Me.RaisePropertyChanged("ID")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Name() As String
            Get
                Return Me.NameField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NameField, value) <> true) Then
                    Me.NameField = value
                    Me.RaisePropertyChanged("Name")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/NewConnect", ReplyAction:="http://tempuri.org/IService1/NewConnectResponse")>  _
        Function NewConnect(ByVal name As String) As ServiceReference1.Player
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/NewConnect", ReplyAction:="http://tempuri.org/IService1/NewConnectResponse")>  _
        Function NewConnectAsync(ByVal name As String) As System.Threading.Tasks.Task(Of ServiceReference1.Player)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SendMessage", ReplyAction:="http://tempuri.org/IService1/SendMessageResponse")>  _
        Sub SendMessage(ByVal text As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/SendMessage", ReplyAction:="http://tempuri.org/IService1/SendMessageResponse")>  _
        Function SendMessageAsync(ByVal text As String) As System.Threading.Tasks.Task
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetChatText", ReplyAction:="http://tempuri.org/IService1/GetChatTextResponse")>  _
        Function GetChatText() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/GetChatText", ReplyAction:="http://tempuri.org/IService1/GetChatTextResponse")>  _
        Function GetChatTextAsync() As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function NewConnect(ByVal name As String) As ServiceReference1.Player Implements ServiceReference1.IService1.NewConnect
            Return MyBase.Channel.NewConnect(name)
        End Function
        
        Public Function NewConnectAsync(ByVal name As String) As System.Threading.Tasks.Task(Of ServiceReference1.Player) Implements ServiceReference1.IService1.NewConnectAsync
            Return MyBase.Channel.NewConnectAsync(name)
        End Function
        
        Public Sub SendMessage(ByVal text As String) Implements ServiceReference1.IService1.SendMessage
            MyBase.Channel.SendMessage(text)
        End Sub
        
        Public Function SendMessageAsync(ByVal text As String) As System.Threading.Tasks.Task Implements ServiceReference1.IService1.SendMessageAsync
            Return MyBase.Channel.SendMessageAsync(text)
        End Function
        
        Public Function GetChatText() As String Implements ServiceReference1.IService1.GetChatText
            Return MyBase.Channel.GetChatText
        End Function
        
        Public Function GetChatTextAsync() As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.GetChatTextAsync
            Return MyBase.Channel.GetChatTextAsync
        End Function
    End Class
End Namespace
